// GENERATED by tools/ktx2-models.mjs — do not edit.
//
// The models that have a GPU-compressed twin in public/models-ktx2/. assets.js
// swaps the URL for anything named here; anything not named here loads from
// public/models/ exactly as it always did, which is what makes a model that
// fails to encode a non-event rather than a missing creature.
//
// A LIST AND NOT A DIRECTORY SCAN because the browser cannot read a directory,
// and the alternative — trying the compressed URL and falling back on a 404 —
// is a wasted round trip per model and, on a host with an SPA fallback, a 200
// carrying index.html that GLTFLoader then tries to parse. See the note in
// [[pages-spa-fallback-hides-404s]].
export const KTX2_MODELS = new Set([
    "anglerfish.glb",
    "ballroomguest.glb",
    "barracuda.glb",
    "barrel.glb",
    "bobblehat.glb",
    "bobhair.glb",
    "bowlerhat.glb",
    "businessguest.glb",
    "clochehat.glb",
    "combjelly.glb",
    "cowboyhat.glb",
    "crabpincer.glb",
    "crownjelly.glb",
    "cutesquid.glb",
    "dancingcrab.glb",
    "fedorahat.glb",
    "fish.glb",
    "fish2.glb",
    "fisherman.glb",
    "fishingboat.glb",
    "fishpack.glb",
    "flowerhatjelly.glb",
    "giantsquid.glb",
    "grass.glb",
    "greatwhite.glb",
    "hardhat.glb",
    "hat.glb",
    "jellyfish.glb",
    "lizardfish.glb",
    "megalodon.glb",
    "mightymeg.glb",
    "moneyroll1.glb",
    "moneyroll2.glb",
    "moneyroll3.glb",
    "moneyroll4.glb",
    "moonjelly.glb",
    "mosasaurus.glb",
    "myllokunmingia.glb",
    "oyster.glb",
    "puffer.glb",
    "roundglasses.glb",
    "sailfish.glb",
    "sardine.glb",
    "shark.glb",
    "sharkhood.glb",
    "shorthair.glb",
    "shrimp.glb",
    "spottedjelly.glb",
    "squid.glb",
    "stetsonhat.glb",
    "tang.glb",
    "trawler.glb",
    "tricornhat.glb",
    "ushankahat.glb",
    "voicemailbomb.glb",
    "wireglasses.glb",
    "wizardhat.glb",
    "yacht.glb"
  ]);
