#!/usr/bin/env node
// ============================================================================
// SEALITAIRE'S LIVE TUNING LOOP.
//
// A Rive script cannot write a file and the CLI viewer has no knob panel, so
// the loop is closed from outside, through the one channel a script has: the
// console. It goes round like this:
//
//   rive/sealitaire/tuning.luau   the rows — key, range, value. Source of truth.
//        │  `gen`
//        ▼
//   rive/sealitaire/tuner.rml     the panel artboard: a label, a value and a
//                                 knob per row, every one data-bound, so the
//                                 script (which cannot draw text) draws it
//        │  npm run sealitaire
//        ▼
//   the live window               click the title, drag knobs; the script
//                                 applies every value on the next frame
//        │  press "save" in the panel → the script prints one line:
//        │    TUNING-SAVE key=value key=value ...
//        │  and, for every card the panel's CARD rows changed, one more:
//        │    TANKS-SAVE card=Q:star model=orca_male count=1 size=1.6 back=#.. belly=#.. bg=#..
//        ▼
//   this tool (`run`)             owns the `rive` watcher, reads its output,
//                                 writes the values back into tuning.luau —
//                                 and the card rows into tanks.csv, cell by
//                                 cell, leaving flip and notes as they were —
//                                 which the watcher sees change and rebuilds,
//                                 so the next launch starts where you left it.
//
//   The CARD rows are the lab: with the panel open, click a card and its
//   tanks.csv row is on the panel — model (every species in fish.mesh; bake
//   the pool with `npm run sealitaire:pool` first), count, size, the three
//   colours — and SUIT copies a number card's look over its suit's 2-10.
//
//   node tools/sealitaire-tune.mjs gen    regenerate tuner.rml (after editing rows)
//   node tools/sealitaire-tune.mjs run    gen, then the viewer with the save loop
// ============================================================================

import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync, spawn } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PROJECT = join(ROOT, 'rive/sealitaire');
const TUNING = join(PROJECT, 'tuning.luau');
const TANKS = join(PROJECT, 'tanks.csv');
const TUNER = join(PROJECT, 'tuner.rml');
const RIVE = process.env.RIVE_CLI || join(process.env.HOME ?? '', '.rive/bin/rive');

// Panel geometry. table.luau's TUNER table repeats these; keep them in step.
const COL_W = 380;
const COLS = 2;
const PANEL_W = COL_W * COLS;
const HEADER = 40;
const ROW_H = 16;
const FOOTER = 44;
const TRACK_X0 = 172;
const TRACK_X1 = 360;

function readRows() {
  const src = readFileSync(TUNING, 'utf8');
  const rows = [];
  const re = /\{\s*key\s*=\s*'([A-Za-z0-9_]+)'\s*,\s*min\s*=\s*([-\d.]+)\s*,\s*max\s*=\s*([-\d.]+)\s*,\s*value\s*=\s*([-\d.]+)\s*(?:,\s*cat\s*=\s*'([A-Za-z0-9_]+)')?\s*\}/g;
  let m;
  while ((m = re.exec(src))) rows.push({ key: m[1], min: +m[2], max: +m[3], value: +m[4], cat: m[5] || '' });
  if (!rows.length) throw new Error(`no rows parsed from ${TUNING}`);
  return rows;
}

function gen() {
  const rows = readRows();
  const n = rows.length;
  const perCol = Math.ceil(n / COLS);
  const h = HEADER + perCol * ROW_H + FOOTER;
  let id = 1;
  const nid = () => `1:${id++}`;
  const out = [];
  out.push('<Rive version="1" kind="fragment">');
  out.push('    <!-- GENERATED by tools/sealitaire-tune.mjs from tuning.luau. Do not edit. -->');
  out.push(`    <Artboard isComponent="true" defaultStateMachineId="1:9000" viewModelId="1:8000" viewModelInstanceId="1:8001"`);
  out.push(`              x="1700" y="1100" width="${PANEL_W}" height="${h}" styleId="${nid()}" name="Tuner" id="1:7000">`);
  out.push(`        <LayoutComponentStyle name="Style" id="1:${id - 1}"/>`);
  // Footer: save / reset labels (tooling text, not a player's).
  out.push(`        <Text x="20" y="${h - 30}" sizingValue="autoWidth" name="Save" id="${nid()}">`);
  out.push(`            <TextStylePaint fontSize="13" letterSpacing="0.08" fontAssetId="0:400" name="S" id="${nid()}">`);
  out.push(`                <Fill name="F" id="${nid()}"><SolidColor colorValue="FFF5B02E" name="C" id="${nid()}"/></Fill>`);
  out.push(`            </TextStylePaint>`);
  out.push(`            <TextValueRun styleId="1:${id - 3}" text="SAVE" name="Run" id="${nid()}"/>`);
  out.push(`        </Text>`);
  out.push(`        <Text x="110" y="${h - 30}" sizingValue="autoWidth" name="Reset" id="${nid()}">`);
  out.push(`            <TextStylePaint fontSize="13" letterSpacing="0.08" fontAssetId="0:400" name="S" id="${nid()}">`);
  out.push(`                <Fill name="F" id="${nid()}"><SolidColor colorValue="FF7FB6E8" name="C" id="${nid()}"/></Fill>`);
  out.push(`            </TextStylePaint>`);
  out.push(`            <TextValueRun styleId="1:${id - 3}" text="RESET" name="Run" id="${nid()}"/>`);
  out.push(`        </Text>`);
  const vm = [];
  const inst = [];
  rows.forEach((r, i) => {
    const colX = Math.floor(i / perCol) * COL_W;
    const y = HEADER + (i % perCol) * ROW_H;
    const cy = y + ROW_H / 2;
    const k = i + 1;
    const lId = `1:${2000 + k}`, vId = `1:${3000 + k}`, kId = `1:${4000 + k}`;
    // label
    out.push(`        <Text x="${colX + 16}" y="${y + 5}" sizingValue="autoWidth" name="L${k}" id="${nid()}">`);
    out.push(`            <TextStylePaint fontSize="12" fontAssetId="0:400" name="S" id="${nid()}">`);
    out.push(`                <Fill name="F" id="${nid()}"><SolidColor colorValue="FFB9D4EE" name="C" id="${nid()}"/></Fill>`);
    out.push(`            </TextStylePaint>`);
    out.push(`            <TextValueRun styleId="1:${id - 3}" text="${r.key}" name="Run" id="${nid()}">`);
    out.push(`                <DataBindContext sourcePathIds="1:8000-${lId}" propertyKey="268" id="${nid()}"/>`);
    out.push(`            </TextValueRun>`);
    out.push(`        </Text>`);
    // value
    out.push(`        <Text x="${colX + TRACK_X0 - 12}" y="${y + 5}" sizingValue="autoWidth" originX="1" name="V${k}" id="${nid()}">`);
    out.push(`            <TextStylePaint fontSize="12" fontAssetId="0:400" name="S" id="${nid()}">`);
    out.push(`                <Fill name="F" id="${nid()}"><SolidColor colorValue="FFF6F1E7" name="C" id="${nid()}"/></Fill>`);
    out.push(`            </TextStylePaint>`);
    out.push(`            <TextValueRun styleId="1:${id - 3}" text="${r.value}" name="Run" id="${nid()}">`);
    out.push(`                <DataBindContext sourcePathIds="1:8000-${vId}" propertyKey="268" id="${nid()}"/>`);
    out.push(`            </TextValueRun>`);
    out.push(`        </Text>`);
    // knob (x bound)
    out.push(`        <Shape x="${colX + TRACK_X0}" y="${cy}" name="K${k}" id="${nid()}">`);
    out.push(`            <DataBindContext sourcePathIds="1:8000-${kId}" propertyKey="13" id="${nid()}"/>`);
    out.push(`            <Ellipse width="12" height="12" originX="0.5" originY="0.5" name="P" id="${nid()}"/>`);
    out.push(`            <Fill name="F" id="${nid()}"><SolidColor colorValue="FFF5B02E" name="C" id="${nid()}"/></Fill>`);
    out.push(`        </Shape>`);
    // track
    out.push(`        <Shape x="${colX + (TRACK_X0 + TRACK_X1) / 2}" y="${cy}" name="T${k}" id="${nid()}">`);
    out.push(`            <Rectangle width="${TRACK_X1 - TRACK_X0}" height="3" originX="0.5" originY="0.5" cornerRadiusTL="1.5" name="P" id="${nid()}"/>`);
    out.push(`            <Fill name="F" id="${nid()}"><SolidColor colorValue="66B9D4EE" name="C" id="${nid()}"/></Fill>`);
    out.push(`        </Shape>`);
    vm.push(`        <ViewModelPropertyString name="l${k}" id="${lId}"/>`);
    vm.push(`        <ViewModelPropertyString name="v${k}" id="${vId}"/>`);
    vm.push(`        <ViewModelPropertyNumber name="k${k}" id="${kId}"/>`);
    inst.push(`            <ViewModelInstanceString propertyValue="${r.key}" viewModelPropertyId="${lId}" id="${nid()}"/>`);
    inst.push(`            <ViewModelInstanceString propertyValue="${r.value}" viewModelPropertyId="${vId}" id="${nid()}"/>`);
    const t = (r.value - r.min) / (r.max - r.min);
    inst.push(`            <ViewModelInstanceNumber propertyValue="${(colX + TRACK_X0 + t * (TRACK_X1 - TRACK_X0)).toFixed(1)}" viewModelPropertyId="${kId}" id="${nid()}"/>`);
  });
  // panel plate, last = bottom
  out.push(`        <Shape x="${PANEL_W / 2}" y="${h / 2}" name="Plate" id="${nid()}">`);
  out.push(`            <Rectangle width="${PANEL_W}" height="${h}" originX="0.5" originY="0.5" cornerRadiusTL="12" name="P" id="${nid()}"/>`);
  out.push(`            <Fill name="F" id="${nid()}"><SolidColor colorValue="D8071A2E" name="C" id="${nid()}"/></Fill>`);
  out.push(`            <Stroke thickness="1.5" name="E" id="${nid()}"><SolidColor colorValue="66B9D4EE" name="C" id="${nid()}"/></Stroke>`);
  out.push(`        </Shape>`);
  out.push(`        <StateMachine name="State Machine 1" id="1:9000">`);
  out.push(`            <StateMachineLayer name="Layer 1" id="1:9001">`);
  out.push(`                <AnyState x="300" y="0" id="1:9002"/><ExitState x="400" y="0" id="1:9003"/><EntryState x="0" y="0" id="1:9004"/>`);
  out.push(`            </StateMachineLayer>`);
  out.push(`        </StateMachine>`);
  out.push(`    </Artboard>`);
  out.push(`    <ComponentAsset artboardId="1:7000" name="Tuner" id="1:7001"/>`);
  out.push(`    <ViewModel defaultInstanceId="1:8001" name="Tuning" id="1:8000">`);
  out.push(...vm);
  out.push(`        <ViewModelInstance exports="true" name="Instance" id="1:8001">`);
  out.push(...inst);
  out.push(`        </ViewModelInstance>`);
  out.push(`    </ViewModel>`);
  out.push('</Rive>');
  writeFileSync(TUNER, out.join('\n') + '\n');
  console.log(`wrote ${TUNER}: ${n} rows in ${COLS} columns, panel ${PANEL_W}x${h}`);
  return rows;
}

// Write `key=value` pairs back into tuning.luau, touching only the value of
// each row and nothing else in the file.
// The cutoff the bank is currently baked at, straight from the file both this
// and the baker read.
function lowpassHz() {
  try {
    const m = /\{\s*key\s*=\s*'sfxLowpass'\s*,[^}]*?value\s*=\s*([-\d.]+)/.exec(readFileSync(TUNING, 'utf8'));
    return m ? Number(m[1]) : 0;
  } catch {
    return 0;
  }
}

// RE-PRINT THE BANK at the new cutoff. Synchronous and about ten seconds: it
// rewrites every take, sfx.csv and scene.rml, which the watcher then reloads
// — so the deal restarts under you. That is the cost of a tone control on a
// runtime with no filter, and it is why this is not silent.
//
// The knock ladder is NOT re-printed here. It is a hundred files resampled
// from the tankWall takes and takes long enough to stall the loop, so it is
// left to a deliberate command — but it IS now stale, and saying so is the
// whole point of the line.
function rebake(from, to) {
  process.stderr.write(`\n[tune] sfxLowpass ${from} -> ${to}Hz: re-printing the bank, ~10s...\n`);
  try {
    execFileSync(process.execPath, [join(ROOT, 'tools/sealitaire-sfx.mjs'), '--write'], { stdio: 'pipe' });
    process.stderr.write('[tune] bank re-printed; the watcher rebuilds\n');
    process.stderr.write('[tune] the knock ladder is now stale — `npm run sealitaire:sfx:fx knock` when you settle\n');
  } catch (err) {
    process.stderr.write(`[tune] re-print FAILED, the bank is still at ${from}Hz: ${err.message}\n`);
  }
}

function save(pairs) {
  const before = readFileSync(TUNING, 'utf8');
  let src = before;
  let changed = 0;
  for (const [key, value] of pairs) {
    const re = new RegExp(`(\\{\\s*key\\s*=\\s*'${key}'\\s*,[^}]*?value\\s*=\\s*)([-\\d.]+)`);
    const next = src.replace(re, (all, head, old) => {
      if (+old !== +value) changed++;
      return head + value;
    });
    src = next;
  }
  // Only touch the file when a value moved: a write is a rebuild, and a
  // rebuild restarts the deal under you.
  if (src !== before) writeFileSync(TUNING, src);
  return changed;
}

// ---------------------------------------------------------------------------
// tanks.csv, one record at a time. The file is parsed with its quoting so a
// notes cell holding commas survives, and every record remembers where its
// own text sits, so a save rewrites the ONE row it names and copies every
// other byte through — the other rows' quoting, their notes, the header.
// ---------------------------------------------------------------------------
function parseCsvSpans(text) {
  const recs = [];
  let row = [], cell = '', q = false, start = 0;
  const flush = (end) => {
    if (row.length || cell.length) { row.push(cell); recs.push({ cells: row, start, end }); }
    row = []; cell = '';
  };
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { cell += '"'; i++; } else q = false; }
      else cell += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(cell); cell = ''; }
    else if (c === '\n') { flush(i); start = i + 1; }
    else if (c !== '\r') cell += c;
  }
  flush(text.length);
  return recs;
}
const csvCell = (v) => (/[",\r\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);

export const TANK_FIELDS = ['model', 'count', 'size', 'back', 'belly', 'bg', 'colGap', 'rowGap', 'padX', 'padY', 'drop', 'rotate', 'rotateVary', 'yaw', 'roll', 'sway', 'loop', 'bio', 'bioColor', 'bioSpeed', 'bioScale', 'bioContrast', 'bioCoverage', 'bioPan', 'bioEvolve'];

/** Apply one TANKS-SAVE line's fields to the tanks.csv text; returns the new
 *  text, or null when the card has no row or nothing moved. Pure, for the test. */
export function applyTankSave(text, fields) {
  const recs = parseCsvSpans(text);
  if (!recs.length) return null;
  const head = recs[0].cells.map((h) => h.trim());
  const col = Object.fromEntries(head.map((h, k) => [h, k]));
  const card = (fields.card || '').replace(':', ' ');
  const rec = recs.slice(1).find((r) => (r.cells[col.card] ?? '').trim() === card);
  if (!rec || col.card == null) return null;
  const cells = rec.cells.slice();
  while (cells.length < head.length) cells.push('');
  let changed = 0;
  // Every cell the panel can write. A key missing here is a slider whose
  // SAVE silently never lands — drop, rotate and rotateVary were exactly
  // that for a while, so the list is checked against the header by the test.
  for (const key of TANK_FIELDS) {
    if (fields[key] == null || col[key] == null) continue;
    if ((cells[col[key]] ?? '').trim() !== fields[key]) { cells[col[key]] = fields[key]; changed++; }
  }
  if (!changed) return null;
  const line = cells.map(csvCell).join(',');
  return text.slice(0, rec.start) + line + text.slice(rec.end);
}

function saveTanks(fields) {
  const before = readFileSync(TANKS, 'utf8');
  const next = applyTankSave(before, fields);
  if (next == null) return false;
  writeFileSync(TANKS, next);
  return true;
}

// ---------------------------------------------------------------------------
// ONE VIEWER AT A TIME.
//
// The viewer is a WRITER: press SAVE and the loop above rewrites tuning.luau
// from the values that window is holding. Two of them means two snapshots of
// that file and the second save wins, silently, over work that was only ever
// on screen in the window that lost.
//
// The check lives HERE rather than in the things that launch it — the Dock
// app, the workbench button, a terminal — because those are three places to
// forget it and this is the one they all go through.
//
// `pgrep -f` matches whole command lines, so the pattern is ANCHORED: without
// the `^` it also matches any process that merely MENTIONS the project path —
// a grep, an editor, another agent session, the shell you typed the check
// into. That is not hypothetical; it fired on exactly that. Only the real
// viewer has the rive binary at the START of its command line, because a
// shell wrapper's argv starts with the shell.
export const BUSY = 3;   // tools/sealitaire-app.mjs turns this one into a dialog

/** The pid of the viewer open on this project, or 0. Exported so the
 *  workbench can show the same answer rather than keeping its own pattern. */
export function tableOpen() {
  try {
    const out = execFileSync('/usr/bin/pgrep', ['-f', `^${RIVE} ${PROJECT}`], { encoding: 'utf8' });
    return Number(out.trim().split('\n')[0]) || 0;
  } catch {
    // pgrep exits 1 with no match, and is simply absent off macOS/Linux.
    // Either way: nothing found, and never a reason to refuse to start.
    return 0;
  }
}

function run() {
  if (tableOpen()) {
    process.stderr.write('\n[tune] a viewer is already open on this project.\n'
      + '       Close that window first — a second one would overwrite its\n'
      + '       tuning the next time you press SAVE.\n\n');
    process.exit(BUSY);
  }
  const child = spawn(RIVE, [PROJECT], { stdio: ['inherit', 'pipe', 'pipe'] });
  let buf = '';
  const onChunk = (chunk, stream) => {
    stream.write(chunk);
    buf += chunk.toString();
    let nl;
    while ((nl = buf.indexOf('\n')) >= 0) {
      const line = buf.slice(0, nl);
      buf = buf.slice(nl + 1);
      const tanksAt = line.indexOf('TANKS-SAVE ');
      if (tanksAt >= 0 && !/\bconsole\s+\S+:\d+/.test(line.slice(0, tanksAt))) {
        const fields = Object.fromEntries(line.slice(tanksAt + 'TANKS-SAVE '.length).trim().split(/\s+/)
          .map((kv) => kv.split('=')).filter((kv) => kv.length === 2 && kv[0]));
        const wrote = saveTanks(fields);
        process.stderr.write(wrote
          ? `\n[tune] tanks.csv: ${(fields.card || '?').replace(':', ' ')} -> ${fields.model} x${fields.count} @${fields.size}; the watcher rebuilds\n`
          : `\n[tune] tanks.csv: ${(fields.card || '?').replace(':', ' ')} unchanged\n`);
        continue;
      }
      const at = line.indexOf('TUNING-SAVE ');
      if (at < 0) continue;
      // The CLI echoes every print a second time as a `console` log line;
      // one save, one write.
      if (/\bconsole\s+\S+:\d+/.test(line.slice(0, at))) continue;
      const pairs = line.slice(at + 'TUNING-SAVE '.length).trim().split(/\s+/)
        .map((kv) => kv.split('='))
        .filter((kv) => kv.length === 2 && kv[0] && Number.isFinite(+kv[1]));
      // The tone is BAKED, so its slider is not like the others: moving it
      // changes nothing until the bank is printed again. Caught here so the
      // panel can carry the control at all — otherwise sfxLowpass is a knob
      // that appears to do nothing, which is worse than no knob.
      const toneBefore = lowpassHz();
      const changed = save(pairs);
      if (changed > 0) {
        process.stderr.write(`\n[tune] saved ${changed} changed value${changed === 1 ? '' : 's'} to tuning.luau; the watcher rebuilds\n`);
      } else {
        process.stderr.write('\n[tune] nothing changed since the last save\n');
      }
      if (lowpassHz() !== toneBefore) rebake(toneBefore, lowpassHz());
    }
  };
  child.stdout.on('data', (c) => onChunk(c, process.stdout));
  child.stderr.on('data', (c) => onChunk(c, process.stderr));
  child.on('exit', (code) => process.exit(code ?? 0));
}

// IMPORTED, NOT RUN, when something only wants tableOpen() — tools/hub.mjs
// does. Without this guard that import starts a viewer, because `cmd` defaults
// to 'run'.
const cmd = process.argv[1] === fileURLToPath(import.meta.url) ? (process.argv[2] ?? 'run') : null;
if (cmd === null) { /* imported */ }
else if (cmd === 'gen') console.log('tuner.rml is static now: the script lays the panel out from tuning.luau, nothing to generate');
else if (cmd === 'run') run();
else if (cmd === 'save') {
  // `save key=value ...` — the same write the run loop does, for a line
  // copied out of a headless run's console.
  const pairs = process.argv.slice(3).map((kv) => kv.split('=')).filter((kv) => kv.length === 2);
  console.log(`saved ${pairs.length} values (${save(pairs)} changed)`);
} else {
  console.error('usage: sealitaire-tune.mjs gen | run | save key=value ...');
  process.exit(2);
}
